name: Test

on:
  push:
    branches: ['*']
    tags: ['!v*']
  workflow_call: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -x
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install bats
      uses: bats-core/bats-action@2.0.0
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run tests
      run: bats . --formatter tap13 tests | tee results.tap
    - name: Generate test summary
      uses: test-summary/action@v2
      with:
        paths: upkg/tests/results.tap
        show: "fail, skip"
      if: always()
